### PR TITLE
minimal fix for Issue #94

### PR DESCRIPTION
**Pull request by emicklei**

### CODE REVIEW

**Comment by nilslice** [comment]
I'm still getting the scanner errors when I try to run my test: 
https://github.com/nilslice/protolock/pull/66

Did you say this was expected, and as a workaround to _not_ use single-quoted reserved names though?

**Comment by emicklei** [comment]
@nilslice  did the tests for proto pass on your machine?

I am hoping that the workaround is not needed ; i deleted my initial comment.

If the problem still exist then could you provide a test for it?

**Comment by emicklei** [comment]
fyi,  i was able to run your tests and see the error mentioned. now i start investigating

**Comment by nilslice** [comment]
Ok, I'm glad I'm not crazy then :) 

Let me know if there is any help I can offer. Thank you!

**Comment by emicklei** [comment]
after spending some time in the debugger, I figured out what is going on.

Adding ScanChars is not the solution. Without this mode, the first single quote is accepted as a char, the literal is a string containing the single quote. Next the scanner actually scans the unquoted string up until, not including the closing single quote. The isString fails to detect this.

Anyway, I have an idea to fix this. Tomorrow, I will continue (23:33 here now).

**Comment by nilslice** [comment]
quite interesting! I'm very much looking forward to your solution.. I'll admit, this is a bit "above my pay-grade" so to speak 😄.. I've learned a lot already from your parser.

**Comment by nilslice** [comment]
@emicklei - this is great, thank you! I have run through your tests on `emicklei/proto`, the updated tests on `nilslice/protolock`, and a manual integration test using `protolock` on single quoted names and everything passes and works properly. 👍 

Once you are ready to merge, would you bump the release version?

**Comment by emicklei** [comment]
thanks,  I created v1.6.6. have fun

**Pull request merged**
