### PR TITLE
 allow multiple values (Literal)for aggregate constant, issue #59

### PR DESCRIPTION
**Pull request by emicklei**

### CODE REVIEW

**Comment by peter-edge** [comment]
I think this is incorrect:

```
+	returns (ListTransferLogsResponse) {
+		option (google.api.http) = {
+		get: "/v1/{parent=projects/*/locations/*/transferConfigs/*/runs/*}/"
+			"transferLogs"
+		};
```

This isn't two values for the option, its the two strings concatenated into one value, ie `"/v1/{parent=projects/*/locations/*/transferConfigs/*/runs/*}/transferLogs"`. I will verify for you but in short, the value for `Source` should be all of this, and `Literals()` should not be needed.

**Comment by peter-edge** [comment]
It's verified, the value for `get` is a single string and this is concatenated here. So this PR should probably be reworked/redone heh.

**Comment by emicklei** [comment]
hmm, I think it was because you mentioned repeated values, I assumed it was going to be a slice. Strange syntax design ; why didn't they just write the concatenated version?

**Comment by peter-edge** [comment]
Not sure, but heh they didn't :-) This is parsed with `protoc`, so we should parse it here.

**Pull request closed without merging**
