### PR TITLE
Fix issue #103

### LINKED ISSUE #103: Issue with double-quoted options
I can diagnose this further later, but you might know immediately where this is. I think parsing of options with quotes is trimming the second quote. See https://github.com/uber/prototool/issues/374.

### PR DESCRIPTION
**Pull request by peter-edge**
Fixes #103.

Please carefully look this over and make sure it seems reasonable.

You shouldn't have to worry about leading `\"` because `strings.TrimLeft` will hit the `\` before the `"`.

### CODE REVIEW

**Comment by peter-edge** [comment]
https://github.com/emicklei/proto/pull/105 needs to be merged first to fix the build.

**Comment by peter-edge** [comment]
Build is now passing.

**Comment by emicklei** [comment]
Thank you for helping getting this fixed that quickly.

The unQuote function trimmed both the double and single quotes.
For a moment, I thought the change did not address single quotes "at the end" but it does.
Also tried escaping the single quotes (yet another unusual case) which passed the test, see https://play.golang.org/p/R29gxbFdyr_M

The change unQuote works for the written test cases. Could not come up with a test that failed.

**Comment by peter-edge** [comment]
Great :-) If you can merge and do a release would super appreciate it, then I can pull it into Prototool :-)

**Pull request merged**
